### ISSUE TITLE
[BE] PR 생성시 테스트 결과 PR 댓글에 추가

### ISSUE THREAD

**Issue by Jinwook94** [Jinwook94/bootme#210]
## 워크플로우 파일 경로
- [bootme/.github/workflows/backend-test-pr.yml](https://github.com/Jinwook94/bootme/blob/main/.github/workflows/backend-test-pr.yml)

<br>

## 워크플로우 파일 설명

1. 테스트 코드를 실행하고 그 결과를 PR의 댓글로 추가함
```yaml
      - name: Post Test Results as PR Comment
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
``` 
- 참고: [EnricoMi/publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action)

<br>

2. 실패한 테스트가 있다면 실패한 코드 라인에 Check 코멘트를 등록함
```yaml
      - name: Post Check Comment on Failed Test Lines
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}
```
- 참고: [mikepenz/action-junit-report](https://github.com/mikepenz/action-junit-report)
